### ISSUE TITLE
errors don’t show up as errors

### ISSUE THREAD

**Issue by zamfofex-dummy** [bcomnes/async-neocities#87]
I’m trying to upload a large directory, which has failed (three times now), but the CLI doesn’t recognise it as an error. (The exit code is also zero.)

~~~
...
Stage applying: 87.08% (846 MB / 971 MB)
Stage applying: 87.08% (846 MB / 971 MB)
Stage applying: 87.09% (846 MB / 971 MB)
Stage applying: 87.09% (846 MB / 971 MB)
Stage applying: 87.09% (846 MB / 971 MB)
Stage applying: 87.09% (846 MB / 971 MB)
Stage applying: 87.10% (846 MB / 971 MB)
Stage applying: 87.11% (846 MB / 971 MB)
Stage applying: 87.11% (846 MB / 971 MB)
Stage applying: 87.11% (846 MB / 971 MB)
Stage applying: 87.11% (846 MB / 971 MB)
Stage applying: 87.11% (846 MB / 971 MB)
Stage applying: 87.11% (846 MB / 971 MB)
Stage applying: 87.11% (846 MB / 971 MB)
Stage applying: 87.11% (846 MB / 971 MB)
Stage applying: 87.11% (846 MB / 971 MB)
Stage applying: 100.00%
Finished error stage.
Deployed to Neocities in 34m:
    Uploaded 150 files
    Orphaned 0 files
    Skipped 596 files
    0 protected files:
~~~

It would probably help me figure out what the underlying issue is if it showed what the error actually is. (I have enough free space on Neocities for it.) For now, I suppose I should probably try using the official Ruby Neocities CLI.

**Comment by bcomnes** [comment]
Error handling needs some work yeah. Sorry, haven't had time to work on it lately. If you get to the bottom if it, happy to land any improvements.

**Comment by bcomnes** [comment]
Started on a rewrite this weekend.

**Comment by bcomnes** [comment]
I rewrote the whole library this weekend. Error handling is much more robust now. It prints the status code, the set of files that were being uploaded as well as the body of the errored response. Closing, but if you are still having issues we can reopen or make a new issue.
